server:
  port: 8077
spring:
  application:
    name: app-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cweijiaweil-github/emartspringcloudconfig.git
          search-paths:
          - emartspringcloudconfig
      label: master	
eureka:
  client:
    service-url:
           defaultZone: http://wjw:123456@172.17.0.3:9100/eureka
    register-with-eureka: true
    fetch-registry: true